### ISSUE TITLE
Soul signs page - "see more"

### ISSUE THREAD

**Issue by angelagilhotra** [kernel-community/signature-economies#134]

**Comment by simonkernel** [comment]
The query currently hardcodes the number of NFTs pulled from the graph to 4 -

https://github.com/kernel-community/signature-economies/blob/main/packages/dapp/src/utils/graph.js#L55

@andytudhope how many NFTs did you want to show?

**Comment by andytudhope** [comment]
At least 14, that is, 3 rows of NFTs before sending people off to the Opensea collection.

**Comment by simonkernel** [comment]
@andytudhope the way the layout is designed, it shows the NFTs horizontally.

I pumped up the # by 3x and you can see the result on staging.

Also note that since these are p5js scripts, the page gets pretty heavy and sluggish the more nfts we show so something to be aware of.

Preview link -
https://staging.sign.kernel.community/signatures

**Comment by andytudhope** [comment]
OK perfect, thank you @simonkernel :pray: 

This will do - let's merge it to prod and be done with this issue.
